# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usutter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(445, 370)
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.Res = QtWidgets.QLabel(Dialog)
        self.Res.setGeometry(QtCore.QRect(70, 50, 101, 16))
        self.Res.setObjectName("Res")
        self.Velocity = QtWidgets.QLabel(Dialog)
        self.Velocity.setGeometry(QtCore.QRect(70, 100, 101, 16))
        self.Velocity.setObjectName("Velocity")
        self.velocity = QtWidgets.QSpinBox(Dialog)
        self.velocity.setEnabled(True)
        self.velocity.setGeometry(QtCore.QRect(160, 100, 101, 21))
        self.velocity.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.velocity.setWrapping(False)
        self.velocity.setFrame(True)
        self.velocity.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.velocity.setSuffix("")
        self.velocity.setMaximum(3000)
        self.velocity.setProperty("value", 200)
        self.velocity.setObjectName("velocity")
        self.unit = QtWidgets.QLabel(Dialog)
        self.unit.setGeometry(QtCore.QRect(290, 100, 91, 16))
        self.unit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.unit.setObjectName("unit")
        self.ResH = QtWidgets.QCheckBox(Dialog)
        self.ResH.setGeometry(QtCore.QRect(180, 50, 91, 19))
        self.ResH.setObjectName("ResH")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 310, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 190, 381, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.stepSize = QtWidgets.QDoubleSpinBox(Dialog)
        self.stepSize.setGeometry(QtCore.QRect(160, 150, 101, 22))
        self.stepSize.setMaximum(10000.0)
        self.stepSize.setSingleStep(0.04)
        self.stepSize.setObjectName("stepSize")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 150, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 51, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/191-Attention.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sutter MP285"))
        self.Res.setText(_translate("Dialog", "Resolution:"))
        self.Velocity.setText(_translate("Dialog", "Velocity:"))
        self.unit.setText(_translate("Dialog", "micron/s"))
        self.ResH.setText(_translate("Dialog", "High"))
        self.label.setText(_translate("Dialog", "High resolution:\n"
"Step size should be multiples of 0.04\n"
"Low resolution:\n"
"Step size should be multiples of 0.2 "))
        self.label_2.setText(_translate("Dialog", "Step size:"))
        self.label_3.setText(_translate("Dialog", "microns/step"))
